name: hrms-web
on:
  push:
    tags:
      - v[0-9]
jobs:
  build-and-push-dockerimages:
    strategy:
      fail-fast: false
      matrix:
        project: [test-web]
    permissions:
      contents: read
      packages: write
    secrets:
      IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
    uses: Calance-US/calance-workflows/.github/workflows/build.yml@v3.0.0
    with:
      image_name: calance-us/${{ matrix.project }}
      image_registry: https://hub.docker.com/repositories/hdhakad54
      image_registry_username: hdhakad54
     # docker_context_path: calance-hr/
     # dockerfile_path: calance-hr/Dockerfile
      
